version: "3.1"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jason
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mythic-plus-teams
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
